### PR TITLE
Bump resolver to lts-22.44, fix imports

### LINKED ISSUE #1: forM_/when not in scope
`cairo-canvas` 0.1.0.0 does not compile with stackage [LTS 22.44 for ghc-9.6.7](https://www.stackage.org/lts-22.44):

```
cairo-canvas                     >     Variable not in scope:
cairo-canvas                     >       forM_ :: [Image] -> (Image -> m0 ()) -> IO a2
cairo-canvas                     >     |  
cairo-canvas                     > 135 |   forM_ (csImages result) $ \(Image s' _ _) -> C.surfaceFinish s'
cairo-canvas                     >     |   ^^^^^
cairo-canvas                     >
...
cairo-canvas                     >     Variable not in scope: when :: Bool -> m1 () -> Render ()
cairo-canvas                     >     |  
cairo-canvas                     > 551 |   when needsRescale $ C.surfaceFinish s''
cairo-canvas                     >     |   ^^^^
```

### PR DESCRIPTION
**Pull request by EarlGray**
Should fix https://github.com/apirogov/cairo-canvas/issues/1

### CODE REVIEW

**Comment by EarlGray** [comment]
I have tested this in https://github.com/EarlGray/vado/commit/5ec4a18b6ab49384a2715dcff13beaee4a53fdca , it works.

**Comment by apirogov** [comment]
Thanks! I'll see if I can create a release. I've not used this in a long time, happy to see that it's still useful to someone :)

**Comment by apirogov** [comment]
FYI, I upstreamed your fix, so I hope that you can use the normal dependency now.

**Comment by EarlGray** [comment]
Thanks, I've updated my depedencies to cairo-canvas-0.1.0.1.
