### ISSUE TITLE
forM_/when not in scope

### ISSUE THREAD

**Issue by EarlGray** [apirogov/cairo-canvas#1]
`cairo-canvas` 0.1.0.0 does not compile with stackage [LTS 22.44 for ghc-9.6.7](https://www.stackage.org/lts-22.44):

```
cairo-canvas                     >     Variable not in scope:
cairo-canvas                     >       forM_ :: [Image] -> (Image -> m0 ()) -> IO a2
cairo-canvas                     >     |  
cairo-canvas                     > 135 |   forM_ (csImages result) $ \(Image s' _ _) -> C.surfaceFinish s'
cairo-canvas                     >     |   ^^^^^
cairo-canvas                     >
...
cairo-canvas                     >     Variable not in scope: when :: Bool -> m1 () -> Render ()
cairo-canvas                     >     |  
cairo-canvas                     > 551 |   when needsRescale $ C.surfaceFinish s''
cairo-canvas                     >     |   ^^^^
```
